# Generated by Django 5.0.7 on 2024-10-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpost',
            options={'ordering': ('pk',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
