# Generated by Django 4.2.1 on 2024-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0003_alter_man_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
