# Generated by Django 5.0.7 on 2024-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0011_alter_man_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Опубликовано'),
        ),
    ]
