# Generated by Django 5.0.7 on 2024-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0013_uploadfiles_alter_man_slug_alter_man_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
