# Generated by Django 5.0.7 on 2024-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0014_man_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='man.tagpost', verbose_name='Теги'),
        ),
    ]
